runtime: python39
instance_class: F1
env: standard
service: default

entrypoint: gunicorn -b :$PORT config.wsgi:application

handlers:
  - url: /static
    static_dir: static/
  - url: .*
    secure: always
    script: auto
