runtime: python39
instance_class: F1
env: standard
service: default

entrypoint: gunicorn -b :$PORT config.wsgi:application

handlers:
  - url: /static
    static_dir: static/
  - url: .*
    secure: always
    script: auto

libraries:
- name: ssl
  version: latest
- name: MySQLdb
  version: latest

env_variables:
  CLOUDSQL_CONNECTION_NAME: myapp-omh:us-central1:omh-app-test
  CLOUDSQL_USER: testuser
  CLOUDSQL_PASSWORD: uhLbcAlIdkxiOvK6
