# Generated by Django 4.0.1 on 2022-01-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anestudy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slug', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, to='anestudy.Category'),
        ),
        migrations.AddField(
            model_name='postarticle',
            name='categories',
            field=models.ManyToManyField(blank=True, to='anestudy.Category'),
        ),
    ]
