# Generated by Django 4.0.1 on 2022-01-14 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anestudy', '0002_category_article_categories_postarticle_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anestudy.postarticle'),
        ),
    ]
