# Generated by Django 4.0.1 on 2022-01-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anestudy", "0003_alter_comment_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="category",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
