# Generated by Django 4.0.1 on 2022-01-08 13:58

import calc.models.nutrition
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slug', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientPhysical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default='')),
                ('sex', models.IntegerField(default='')),
                ('height', models.IntegerField(default='')),
                ('weight', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('slug', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.CharField(default=calc.models.nutrition.create_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('energy', models.IntegerField(default='')),
                ('sugar', models.IntegerField(default='')),
                ('protein', models.IntegerField(default='')),
                ('lipid', models.IntegerField(default='')),
                ('water', models.IntegerField(default='')),
                ('salt', models.IntegerField(default='')),
                ('potassium', models.IntegerField(default='')),
                ('image', models.ImageField(blank=True, default='', upload_to=calc.models.nutrition.upload_image_to)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calc.category')),
                ('tags', models.ManyToManyField(blank=True, to='calc.Tag')),
            ],
        ),
    ]
