name: deploy
on: push

jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
    - uses: 'actions/checkout@v2'
    - shell: bash
      run: |
        touch .env
        echo "${{ secrets.OMHAPP }}" >> .env

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        service_account: 'omh-site-app@myapp-omh.iam.gserviceaccount.com'

    - name: 'Setup Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      with:
        project_id: '${{ env.PROJECT_ID }}'
        service_account_key: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Deploy to App Engine'
      run: 'gcloud app deploy app.yaml --quiet --no-promote --version v1'



