name: ci
on: push

jobs:
  deplay-staging:
    name: Deploy to Google App Engine
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v0

      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: app.yaml
          credentials: ${{ secrets.GCP_SA_KEY }}
          version: v1
