name: deploy
on: push

jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
    - uses: 'actions/checkout@v2'

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        service_account: 'omh-site-app@myapp-omh.iam.gserviceaccount.com'

    - name: 'Deploy to App Engine'
      uses: 'google-github-actions/deploy-appengine@v0'

      with:
        deliverables: 'app.yaml'
        promote: false
        version: 'v1'
        project_id: '${{ secrets.GCP_PROJECT_ID }}'

    - shell: bash
      run: |
        touch .env
        echo "omhapp=${{ secrets.omhapp }}" >> .env

