name: myapp-omh-deploy
on: push

jobs:
  deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Google App Engine
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          project_id: omh-site-app
          service_account: 'omh-site-app@myapp-omh.iam.gserviceaccount.com'
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          deliverables: app.yaml
