name: deploy
on: push

jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
    - uses: 'actions/checkout@v2'
    - shell: bash
      run: |
        touch .env
        echo "${{ secrets.OMHAPP }}" >> .env

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        service_account: 'omh-site-app@myapp-omh.iam.gserviceaccount.com'

    - name: 'Deploy to App Engine'
      uses: 'google-github-actions/deploy-appengine@v0'

      with:
        deliverables: 'app.yaml'
        promote: false
        version: 'v1'
        project_id: '${{ secrets.GCP_PROJECT_ID }}'

    - name: compose-run
      shell: bash
      env:
        SQL_SECRET: ${{ secrets.SQL_SECRET }}
      run: |
        docker-compose up -d --build
        docker-compose exec -i omh-app_web_1 bash

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py makemigrations
        python manage.py migrate
